### ISSUE TITLE
Is possible separate login page to independent client 

### ISSUE THREAD

**Issue by keryhu** [spring-guides/tut-spring-security-and-angular-js#133]
refer to oauth2 jwt example. Is possible separate login page to independent client ?

want to implement: 

1. authServer build a **CustomLogin** controller replace default authServer FormLogin("/login")

  

>  (why? default formLogin return a html page **'/successPage' or '/login?err'**  after successfully logged in, and return  codeStatus always 200,regardless of the user name, the password is correct;  

> Based on the results above, my client, no way to judge the success or failure of the user login!
> 
> So I want a "/CustomLogin" post controller in authServer , authenticate username and password,
> when authenticate successfully , it return ResponseEntity.ok(true) or else ResponseEntity.ok(true)

2. client post a request to the OAuth2 server with username and password Json object from client .
3. after login, AuthServer store the authentication session,SecurityContext, then client did not need carry access_token every quest

Is it possible? or any Better method implement it ?

**Comment by dsyer** [comment]
You can implement authentication in the auth server in any way you like. I didn't follow the question really, and it seems like you are confused about how the sample works (there's no javascript in the auth server, and the client in the UI app does not have access to any access tokens), or else maybe are not referring to the sample at all (in which case this is the wrong forum).

**Comment by keryhu** [comment]
I referring oauth2 authServer , there is "login.ftl" ,,,if above can implement , can give some advice above how implement **CustomLogin controller** 

I try this: but it did not store authentication context 

```
@PostMapping("/customLogin")
    public ResponseEntity login(@RequestBody LoginDto dto){

        Authentication request = new UsernamePasswordAuthenticationToken(
                dto.getUsername(), dto.getPassword());

        Authentication result = customAuthenticationProvider.authenticate(request);
        SecurityContextHolder.getContext().setAuthentication(result);

        Map<String ,Boolean> map=new HashMap<>();
        map.put("result",true);
        return ResponseEntity.ok(map);

    }

```

**Comment by dsyer** [comment]
I'm still not quite sure what you are trying to do here. Using a `@PostMapping` to handle authentication is an interesting idea though. I never saw that before. You might want to use a `SavedRequestAwareAuthenticationSuccessHandler` to handle a successful response, rather than returning a `ResponseEntity`, I suspect (that way it will behave like a normal login filter). But your handler with a `@RequestBody` makes no sense to me still as an authentication handler for an auth server. I don't really think this question is in scope for this guide (and hence this tracker) though.

**Comment by keryhu** [comment]
I don't know how to achieve my plan。

because I use angular2, I think the login page on the angular2 (angular2 own port), only spring background data transfer。 

if like login.ftl, I have to choose a angular2 to build a similar login.ftl; at the same time I want to use oauth2 authorized session, do not want to use stateless, （Because when using the stateless, call the spring websocket session encountered a problem, no way to deal with）

Based on the above situation, I just think of, how can we maintain the spring authorized session is angular2

**Comment by dsyer** [comment]
I don't think you ought to be handling the OAuth2 flow in angular. It's not designed to work that way. If I were you I'd just use server side templating for dynamic content. It's much easier. Or use angular to make it look nice, but still use the server to handle forms and redirects.

**Comment by keryhu** [comment]
Perhaps as double example, the use of  spring sesssion to manage authorization and session more in line with and  angular2 client combination, it should be able to achieve a similar function like spring oauth2 ...

**Comment by dsyer** [comment]
Well, from where I'm standing you appear to be just making your life difficult because you like angular and want to use it for everything, even if it's not a good fit. I think we can close the issue though, since it isn't relevant to this tutorial. Thanks for the interest, and I hope you find something that works for you.
