### ISSUE TITLE
User-defined confirm_access without JWT tokens ?

### ISSUE THREAD

**Issue by jke1968** [spring-guides/tut-spring-security-and-angular-js#145]
After some experimenting with this excellent example, I am wondering if it is possible to get both the custom login page and the confirm access page without having to use the JWT tokens, i.e. to solely rely on the /user endpoint for authorization like in the oauth2Vanilla example that is also provided in this project.

I am not stating that the solution using JWT tokens is not a good idea (especially for the requests from the resource server) - I'm asking just for me to get a better understanding of the underlying mechanisms of OAuth and Spring Security. 

The background of my question is that I tried to run the example without the JWT related configuration bean and overrides and got a "Invalid CSRF token" on the authentication servers' /authorize endpoint just after pressing the "approve" button. This led to a redirect to the /login endpoint on the UIServer with the following URL : localhost/login?error=access_denied&error_description=User%20denied%20access&state=Y6Qmbg

Any hints as to what I have probably done wrong ?

**Comment by dsyer** [comment]
I think you are confused about the role of JWT in this flow (it's just the token format, nothing to do with the access confirmation)

The CSRF error could be caused by a number of things, so hard to say without more data. Since it is unrelated to the other question in this issue, please take it somewhere else (e.g. StackOverflow) if you want more help with that. My best guess, since it's a common error, is you have two apps using the same cookie path on the same host (localhost?), so the cookie that you need for the confirmation page is the wrong one in the browser.
