### ISSUE TITLE
oauth2-vanilla Resource Server asking for Basic auth, not Bearer

### ISSUE THREAD

**Issue by peterboni** [spring-guides/tut-spring-security-and-angular-js#6]
Hi Dave,

Wondering if I'm missing something simple. The `oauth2-vanilla` project, `resource` server is asking for `Basic` auth, not `Bearer`?

`authserver` is started, and looks like `resource` server has correct `application.properties` entry:

```
spring.oauth2.resource.userInfoUri: http://localhost:9999/uaa/user
```

Here's what happens ...

```
curl -v localhost:9000
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:9000
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Basic realm="Spring"
...
{"timestamp":1423990178614,"status":401,"error":"Unauthorized","message":"Full authentication is required to access this resource","path":"/"}
```

As per [your blog post](https://spring.io/blog/2015/02/03/sso-with-oauth2-angular-js-and-spring-security-part-v) it should do this ...

```
$ curl -v localhost:9000
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:9000
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
...
< WWW-Authenticate: Bearer realm="null", error="unauthorized", error_description="An Authentication object was not found in the SecurityContext"
< Content-Type: application/json;charset=UTF-8
{"error":"unauthorized","error_description":"An Authentication object was not found in the SecurityContext"}
```

Thanks,
Pete.

**Comment by dsyer** [comment]
I think the original published code had this problem because of a bug in the resource server. It works for me now anyway.

**Comment by zerosith** [comment]
Hi.  

I'm running the same example and have the same problem, the only difference with the tutorial is that I'm implementing it with java instead of groovy.

my curl message is

```
* Rebuilt URL to: localhost:9000/
*   Trying ::1...
*   Trying 127.0.0.1...
* C1onnected to localhost (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
...
< WWW-Authenticate: Bearer realm="oauth2-resource", error="unauthorized", error_description="Full authentication is required to access this resource"
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Fri, 10 Jul 2015 16:51:09 GMT
<
{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}* Connection #0 to host localhost left intact
```

could you give a hand with this??

thanks in advance

**Comment by dsyer** [comment]
The difference between Java and Groovy is, well, nothing, so I might suggest that there is something else that is different about your system. If you have a minimal project that reproduces your problem (e.g. one that just converts the blog code to groovy), please post it as a separate issue, since this one is closed. I would be more than happy to try it out and suggest changes on your side or ours.

**Comment by reypader** [comment]
I'm posting a comment here in case anyone comes across this ticket because they somehow encounter the same problem.

Make sure you have both `@EnableResourceServer` and `@EnableAuthorizationServer` in your `AuthServerApplication`.

**Comment by timwebster9** [comment]
If you run the sample projects as they are right from Github, this problem appears, exactly like @peterboni is saying.

@dsyer if it is a bug, and is now fixed, what release is it fixed in?  Should it work as is?  I've created a new issue for this (#45) as I've tried everything I can think of and can't get it to work as shown.
