### ISSUE TITLE
Return code 403 when hitting the resource URL via the gateway

### ISSUE THREAD

**Issue by jpotts** [spring-guides/tut-spring-security-and-angular-js#67]
The "double" example, which has separate web apps for the gateway, UI, admin, and resource servers works as documented in the tutorial. However, I am noticing that if I use curl to hit the resource endpoint via the gateway, the return code is 403, even though the auth succeeds and the cookie is set by the gateway.

Here is that interaction:

```
curl -v -uadmin:admin localhost:8080/resource
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
* Server auth using Basic with user 'admin' 
> GET /resource HTTP/1.1
> Host: localhost:8080
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.46.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Server: Apache-Coyote/1.1
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Set-Cookie: XSRF-TOKEN=a206ad48-c1dc-40e3-83b8-c73a0ed7f577; Path=/
< X-Application-Context: bootstrap
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Set-Cookie: SESSION=b84c21b7-98e9-48f7-8c3b-f17c98025690; Path=/; HttpOnly
< Date: Fri, 22 Jan 2016 22:52:24 GMT
< Set-Cookie: SESSION=2da8af6f-79bc-4222-8f9e-1e52a9e646bf; Path=/; HttpOnly
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"timestamp":1453503144199,"status":403,"error":"Forbidden","message":"Access Denied","path":"/"}
```

The only way I've been able to use curl to hit the resource end point via the gateway is to tell curl to save the cookies, like this:

```
curl -c cookies.txt -v -uadmin:admin localhost:8080/resource
```

Then hit it again using those cookies, like this:

```
curl -b cookies.txt localhost:8080/resource
{"id":"479517a0-41ae-40aa-8eb9-3361351add26","content":"Hello World"}
```

The way this manifests itself in the browser is that a basic auth dialog is presented, followed by the whitelabel error page (403). If you then simply reload the page, the call succeeds, presumably because by that point the cookie has been set.

**Comment by praveen12bnitt** [comment]
I am having the same issue. Is there any solution, workaround for this?

**Comment by dsyer** [comment]
It's not an issue is it? You need to send a cookie to authenticate with the backend. Or am I missing something?

**Comment by jpotts** [comment]
The point is that the API is setting the cookie but the app behind the
gateway isn't reading it immediately, so two login boxes are presented.

**Comment by praveen12bnitt** [comment]
I was planning to use this pattern to expose rest endpoints. Since the cookie does not reach the backend, the first request always fails. If i send the cookie in the second request, it passes. 

May be this approach works well only for webapps, which has a separate login step. In my case, i am directly hitting the rest endpoint for getting data, using basic auth..  May be oauth?

**Comment by dsyer** [comment]
Right I get it, this is a duplicate of #15 and https://jira.spring.io/browse/SEC-2891. Please follow up there.

@praveen12bnitt I didn't understand your point, but it doesn't seem relevant, since the tutorial is about a web app with a back end service. If your client is not a browser (I'm guessing that's what you mean), you would use a different pattern (not cookies).
